In [1]:
import requests
import json

In [2]:
unfiltered_endpoint="/api/get/investment/Company/filter/"
company_search="Foodies Restaurant"

url=f"http://localhost:8080{unfiltered_endpoint}{company_search}"

In [8]:
body=requests.get(url).json()

In [14]:
import pandas as pd
df=pd.DataFrame(body)

In [15]:
df

,_id,Company,Company_Investor,Domicile,Year_Of_Operation,Business,Percentage_Ownership,Revenue,Expense,Ebida,Tax_Investment,Price_Asset,Price_Liability,Equity,COGS,Date_Of_Ownership,__v
0,67607a7dadf8a783ab27da95,Foodies Restaurant,Great Investors,Jakarta,2017,F&B,12,1662008,438454,1150954,230190,4342662,1449143,2893519,72600,2012-01-25T00:00:00.000Z,0
1,67607a7dadf8a783ab27da9e,Foodies Restaurant,Great Investors,Bali,2004,F&B,44,988457,323304,471830,94366,8202812,4933553,3269259,193323,2023-10-04T00:00:00.000Z,0
2,67607a7dadf8a783ab27daa0,Foodies Restaurant,Venture Builders,Semarang,2004,F&B,19,1197507,1008165,31973,6394,2074809,769648,1305161,157369,2012-02-14T00:00:00.000Z,0
3,67607a7dadf8a783ab27daa3,Foodies Restaurant,Venture Builders,Jakarta,2003,F&B,29,2769541,917953,1793691,358738,4066696,2723697,1342999,57897,2019-02-09T00:00:00.000Z,0
4,67607a7dadf8a783ab27daa4,Foodies Restaurant,Green Capital,Bekasi,2006,F&B,77,3682873,2431897,1165441,233088,3736957,1308799,2428158,85535,2011-03-03T00:00:00.000Z,0
5,67607a7dadf8a783ab27daa8,Foodies Restaurant,Beverage Lovers,Singapore,2008,F&B,61,3662680,1189174,2339767,467953,5832763,708475,5124288,133739,2012-04-23T00:00:00.000Z,0
6,67607a7dadf8a783ab27daab,Foodies Restaurant,Global Ventures,Bekasi,2001,F&B,100,3659597,1274565,2219046,443809,6640270,3004557,3635713,165986,2018-04-14T00:00:00.000Z,0
7,67607a7dadf8a783ab27daad,Foodies Restaurant,Green Capital,Semarang,2020,F&B,80,4910083,4154631,668561,133712,1231683,721408,510275,86891,2020-05-18T00:00:00.000Z,0
8,67607a7dadf8a783ab27dab0,Foodies Restaurant,Great Investors,Bekasi,2011,F&B,38,4941115,2557915,2300194,460038,5079101,3211121,1867980,83006,2015-07-01T00:00:00.000Z,0
9,67607a7dadf8a783ab27dab3,Foodies Restaurant,Global Ventures,Jakarta,2009,F&B,65,1011003,804551,112254,22450,7425999,2075365,5350634,94198,2023-01-10T00:00:00.000Z,0
10,67607a7dadf8a783ab27dab8,Foodies Restaurant,Venture Builders,Tangerang,2000,F&B,55,3898332,2760413,1073506,214701,2655459,578221,2077238,64413,2015-03-07T00:00:00.000Z,0
11,67607a7dadf8a783ab27dab9,Foodies Restaurant,Venture Builders,Semarang,2006,F&B,37,1892946,1240967,586125,117225,5165353,1424909,3740444,65854,2014-08-30T00:00:00.000Z,0
12,67607a7dadf8a783ab27dabb,Foodies Restaurant,Great Investors,Singapore,2021,F&B,16,1027302,704640,146748,29349,9287375,2299085,6988290,175914,2011-10-10T00:00:00.000Z,0
13,67607a7dadf8a783ab27dac3,Foodies Restaurant,Global Ventures,Semarang,2009,F&B,79,1831834,1414346,268223,53644,6469922,1323044,5146878,149265,2014-01-21T00:00:00.000Z,0
14,67607a7dadf8a783ab27dac4,Foodies Restaurant,Venture Builders,Jakarta,2017,F&B,84,4625493,1061958,3513376,702675,1159856,670630,489226,50159,2020-09-24T00:00:00.000Z,0
15,67607a7dadf8a783ab27dac5,Foodies Restaurant,Beverage Lovers,Tangerang,2002,F&B,54,4073468,2409018,1585532,317106,7418403,4329549,3088854,78918,2011-04-29T00:00:00.000Z,0

In [18]:
df.drop(columns=["_id","__v"],inplace=True, errors='ignore')
df

,Company,Company_Investor,Domicile,Year_Of_Operation,Business,Percentage_Ownership,Revenue,Expense,Ebida,Tax_Investment,Price_Asset,Price_Liability,Equity,COGS,Date_Of_Ownership
0,Foodies Restaurant,Great Investors,Jakarta,2017,F&B,12,1662008,438454,1150954,230190,4342662,1449143,2893519,72600,2012-01-25T00:00:00.000Z
1,Foodies Restaurant,Great Investors,Bali,2004,F&B,44,988457,323304,471830,94366,8202812,4933553,3269259,193323,2023-10-04T00:00:00.000Z
2,Foodies Restaurant,Venture Builders,Semarang,2004,F&B,19,1197507,1008165,31973,6394,2074809,769648,1305161,157369,2012-02-14T00:00:00.000Z
3,Foodies Restaurant,Venture Builders,Jakarta,2003,F&B,29,2769541,917953,1793691,358738,4066696,2723697,1342999,57897,2019-02-09T00:00:00.000Z
4,Foodies Restaurant,Green Capital,Bekasi,2006,F&B,77,3682873,2431897,1165441,233088,3736957,1308799,2428158,85535,2011-03-03T00:00:00.000Z
5,Foodies Restaurant,Beverage Lovers,Singapore,2008,F&B,61,3662680,1189174,2339767,467953,5832763,708475,5124288,133739,2012-04-23T00:00:00.000Z
6,Foodies Restaurant,Global Ventures,Bekasi,2001,F&B,100,3659597,1274565,2219046,443809,6640270,3004557,3635713,165986,2018-04-14T00:00:00.000Z
7,Foodies Restaurant,Green Capital,Semarang,2020,F&B,80,4910083,4154631,668561,133712,1231683,721408,510275,86891,2020-05-18T00:00:00.000Z
8,Foodies Restaurant,Great Investors,Bekasi,2011,F&B,38,4941115,2557915,2300194,460038,5079101,3211121,1867980,83006,2015-07-01T00:00:00.000Z
9,Foodies Restaurant,Global Ventures,Jakarta,2009,F&B,65,1011003,804551,112254,22450,7425999,2075365,5350634,94198,2023-01-10T00:00:00.000Z
10,Foodies Restaurant,Venture Builders,Tangerang,2000,F&B,55,3898332,2760413,1073506,214701,2655459,578221,2077238,64413,2015-03-07T00:00:00.000Z
11,Foodies Restaurant,Venture Builders,Semarang,2006,F&B,37,1892946,1240967,586125,117225,5165353,1424909,3740444,65854,2014-08-30T00:00:00.000Z
12,Foodies Restaurant,Great Investors,Singapore,2021,F&B,16,1027302,704640,146748,29349,9287375,2299085,6988290,175914,2011-10-10T00:00:00.000Z
13,Foodies Restaurant,Global Ventures,Semarang,2009,F&B,79,1831834,1414346,268223,53644,6469922,1323044,5146878,149265,2014-01-21T00:00:00.000Z
14,Foodies Restaurant,Venture Builders,Jakarta,2017,F&B,84,4625493,1061958,3513376,702675,1159856,670630,489226,50159,2020-09-24T00:00:00.000Z
15,Foodies Restaurant,Beverage Lovers,Tangerang,2002,F&B,54,4073468,2409018,1585532,317106,7418403,4329549,3088854,78918,2011-04-29T00:00:00.000Z

In [19]:
df["Date_Of_Ownership"]=pd.to_datetime(df["Date_Of_Ownership"])
df["Date_Of_Ownership"]=df["Date_Of_Ownership"].dt.date

df

,Company,Company_Investor,Domicile,Year_Of_Operation,Business,Percentage_Ownership,Revenue,Expense,Ebida,Tax_Investment,Price_Asset,Price_Liability,Equity,COGS,Date_Of_Ownership
0,Foodies Restaurant,Great Investors,Jakarta,2017,F&B,12,1662008,438454,1150954,230190,4342662,1449143,2893519,72600,2012-01-25
1,Foodies Restaurant,Great Investors,Bali,2004,F&B,44,988457,323304,471830,94366,8202812,4933553,3269259,193323,2023-10-04
2,Foodies Restaurant,Venture Builders,Semarang,2004,F&B,19,1197507,1008165,31973,6394,2074809,769648,1305161,157369,2012-02-14
3,Foodies Restaurant,Venture Builders,Jakarta,2003,F&B,29,2769541,917953,1793691,358738,4066696,2723697,1342999,57897,2019-02-09
4,Foodies Restaurant,Green Capital,Bekasi,2006,F&B,77,3682873,2431897,1165441,233088,3736957,1308799,2428158,85535,2011-03-03
5,Foodies Restaurant,Beverage Lovers,Singapore,2008,F&B,61,3662680,1189174,2339767,467953,5832763,708475,5124288,133739,2012-04-23
6,Foodies Restaurant,Global Ventures,Bekasi,2001,F&B,100,3659597,1274565,2219046,443809,6640270,3004557,3635713,165986,2018-04-14
7,Foodies Restaurant,Green Capital,Semarang,2020,F&B,80,4910083,4154631,668561,133712,1231683,721408,510275,86891,2020-05-18
8,Foodies Restaurant,Great Investors,Bekasi,2011,F&B,38,4941115,2557915,2300194,460038,5079101,3211121,1867980,83006,2015-07-01
9,Foodies Restaurant,Global Ventures,Jakarta,2009,F&B,65,1011003,804551,112254,22450,7425999,2075365,5350634,94198,2023-01-10
10,Foodies Restaurant,Venture Builders,Tangerang,2000,F&B,55,3898332,2760413,1073506,214701,2655459,578221,2077238,64413,2015-03-07
11,Foodies Restaurant,Venture Builders,Semarang,2006,F&B,37,1892946,1240967,586125,117225,5165353,1424909,3740444,65854,2014-08-30
12,Foodies Restaurant,Great Investors,Singapore,2021,F&B,16,1027302,704640,146748,29349,9287375,2299085,6988290,175914,2011-10-10
13,Foodies Restaurant,Global Ventures,Semarang,2009,F&B,79,1831834,1414346,268223,53644,6469922,1323044,5146878,149265,2014-01-21
14,Foodies Restaurant,Venture Builders,Jakarta,2017,F&B,84,4625493,1061958,3513376,702675,1159856,670630,489226,50159,2020-09-24
15,Foodies Restaurant,Beverage Lovers,Tangerang,2002,F&B,54,4073468,2409018,1585532,317106,7418403,4329549,3088854,78918,2011-04-29

In [20]:
import matplotlib as plt